import os
import arcpy

# BACKUP OLD DATA WITH DATE ATTACHED. 




# SELECT ALL FROM PREVIEW LAYER AND DELETE.  SAVE EDITS.



# RE-CREATE GEOMETRY IN PREVIEW LAYER.  SAVE EDITS.



# OPEN QC MAP WITH INSTRUCTIONS TO CHECK, THEN REPLACE DATA IN FINAL LAYER.
